name: Run & Build Fire Map

on:
  schedule:
    - cron: "0 8 * * *" #minute, hour, day, month, year. CronGuru tool, asterisk means "every"
  workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node. js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Please work for me
      run: npm run build
