name: NodeJS with Grunt

on:
  schedule:
    - cron: "0 8,12 * * 1-5" #minute, hour, day, month, year. CronGuru tool, asterisk means "every"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install grunt & packages
      run: npm install grunt
    - name: Scrape
      run: npm run scrape
    - name: Scrape again, compile and handoff to server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: npm run build
