name: NodeJS with Grunt

on:
  schedule:
    - cron: "0 8,12 * * 1-5" #minute, hour, day, month, year. CronGuru tool, asterisk means "every"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install grunt & packages
      run: npm install grunt
    - name: Scrape
      run: npm run scrape
    - name: Scrape again, compile and handoff to server
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: | 
           npm run build
      id: get-me-fire-names
    - name: Read package.json
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./src/js/fire_data/fireNames.txt
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
    - name: Slack Notification on SUCCESS
      if: (success())
      uses: tokorom/action-slack-incoming-webhook@main
      env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
          text: A successful scrape!
          attachments: |
              [
              {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                  {
                  "title": "GitHub Actions URL",
                  "value": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  },
                  {
                  "title": "Today's fires:",
                  "value": "${{ steps.get-me-fire-names.outputs.FIRES }}"
                  }
                ]
              }
              ]
    - name: Slack Notification on FAILURE
      if: failure()
      uses: tokorom/action-slack-incoming-webhook@main
      env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
          text: Something went wrong.
          attachments: |
              [
              {
              "color": "bad",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                  {
                  "title": "GitHub Actions URL",
                  "value": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                ]
              }
              ]
      
